#!/bin/bash
# sqlline - Script to launch SQL shell

# Build classpath on first call. (To force rebuild, remove cp.txt.)
if [ ! -f cp.txt ]; then
    mvn install -DskipTests
    mvn dependency:build-classpath -Dmdep.outputFile=cp.txt
fi

exec java -cp "target/classes:target/test-classes:$(cat cp.txt)" sqlline.SqlLine "$@"

# End sqlline
